# SOP Python circleci file

version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build
          command: pip3 install -r test-requirements.txt
      - run:
          name: Run tests
          command: python -m pytest pywebpush
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_and_test:
    jobs:
      - build_and_test
