SERVER:
  MIN_SSIM_VS_INIT: 0.7
  MIN_SSIM_VS_NEXT: 0.7

  POST_DETECTION:
    SECS_DEL_KEYS: 5
    CAM_CAP_INTERVAL: 1

  KEEP_PHOTOS_IN_MEM_FOR: 36000
  KEEP_PHOTOS_IN_DISK_FOR: 360000

CLIENT:
  MAX_NUM_PHOTOS_IN_MEM: 36000
  SECS_PHOTOS_TO_MOVE_TO_FREE_MEM: 12000
